x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      golangVersions:
        type: array
        default: []
        items:
          type: string
      customCertificateData:
        type: object
        properties:
          tls.crt:
            type: string
            x-examples:
              - plainstring
          tls.key:
            type: string
            x-examples:
              - plainstring
          ca.crt:
            type: string
            x-examples:
              - plainstring
  registry:
    type: object
    description: "System field, overwritten by Deckhouse. Don't use"
