{{- if eq (include "helm_lib_module_gateway_enabled" .) "true" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: main
  namespace: {{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "echoserver")) | nindent 2 }}
spec:
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . "echoserver") }}
    name: echoserver
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: {{ include "helm_lib_module_https_secret_name" (list . "ingress-tls" "httproute-tls") }}
        namespace: {{ .Chart.Name }}
      mode: Terminate
{{- end }}
